enableScripts: true

nodeLinker: node-modules

packageExtensions:
  "@astrojs/compiler-binding-wasm32-wasi@*":
    dependencies:
      "@emnapi/core": "^1.11.1"
      "@emnapi/runtime": "^1.11.1"
  "@astrojs/language-server@*":
    dependencies:
      typescript: "^5.0.0 || ^6.0.0"
