authors = ["Mitchell Hynes <me@mitchellhynes.com>"]
name = "backend"
spin_version = "1"
trigger = {type = "http", base = "/"}
version = "1.0.0"

[variables]
discord_bot_token = {required = true}
discord_pub_key = {required = true}
redis_address = {default = "", required = true}

[[component]]
description = "Serves the statically built content"
files = [{source = "public/", destination = "/"}]
id = "static"
source = "functions/static/target/wasm32-wasi/release/static.wasm"
[component.trigger]
route = "/..."
[component.build]
command = "cargo run && cd functions/static && cargo build --target wasm32-wasi --release"

[[component]]
allowed_http_hosts = ["https://mitchellhynes.com/"]
description = "Like/Unlike a page"
environment = {JWT_SECRET = "bababoey", REDIS_CHANNEL = "messages"}
id = "likes"
source = "functions/tokenize/target/wasm32-wasi/release/tokenize.wasm"
[component.trigger]
route = "/likes"
[component.build]
command = "cargo run && cd functions/tokenize && cargo build --target wasm32-wasi --release"

[[component]]
allowed_http_hosts = ["https://discord.com"]
description = "A discord bot"
environment = {DISCORD_PUB_KEY = "{{discord_pub_key}}", DISCORD_BOT_TOKEN = "{{discord_bot_token}}"}
id = "bot"
source = "functions/bot/target/wasm32-wasi/release/bot.wasm"
[component.trigger]
route = "/api/interactions"
[component.build]
command = "cargo run && cd functions/bot && cargo build --target wasm32-wasi --release"

[[component]]
description = "A fun microservice that 'splains'"
id = "splain"
source = "functions/splain/target/wasm32-wasi/release/splain.wasm"
[component.trigger]
route = "/splain"
[component.build]
command = "cargo run && cd functions/splain && cargo build --target wasm32-wasi --release"
