authors = ["Mitchell Hynes <me@mitchellhynes.com>"]
name = "backend"
spin_version = "1"
trigger = {type = "http", base = "/"}
version = "1.0.0"

[config]
redis_address = {default = "", required = true}

[[component]]
files = [{source = "public/", destination = "/"}]
id = "static"
source = "functions/static/target/wasm32-wasi/release/static.wasm"
[component.trigger]
route = "/..."
[component.build]
command = "cargo run && cd functions/static && cargo build --target wasm32-wasi --release"

[[component]]
allowed_http_hosts = ["https://mitchellhynes.com/"]
environment = {JWT_SECRET = "bababoey", REDIS_ADDRESS = "{{ redis_address }}", REDIS_CHANNEL = "messages"}
id = "likes"
source = "functions/tokenize/target/wasm32-wasi/release/tokenize.wasm"
[component.trigger]
route = "/likes"

[[component]]
id = "splain"
source = "functions/splain/target/wasm32-wasi/release/splain.wasm"
[component.trigger]
route = "/splain"
