spin_version = "1"
authors = ["Mitchell Hynes <me@mitchellhynes.com>"]
name = "backend"
trigger = { type = "http", base = "/" }
version = "1.0.0"

[[component]]
environment = { REDIS_ADDRESS = "redis://127.0.0.1:6379", REDIS_CHANNEL = "messages" }
allowed_http_hosts = [ "https://mitchellhynes.com/" ]
id = "token"
source = "tokenize/target/wasm32-wasi/release/tokenize.wasm"
[component.trigger]
route = "/token"
[component.build]
command = "cd tokenize && cargo build --target wasm32-wasi --release"
