title = "Rust Sloth"
description = "Rust Library and CLI for generating ASCII art from 3D Models"
link = "https://github.com/ecumene/rust-sloth"
image = "/pikachu.png"
tags = ["rust", "700 stars", "cli"]
