[package]
edition = "2021"
name = "mitch-outline"
version = "0.1.0"

[lib]
name = "mitch_outline"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.0"
image = "0.24.2"
