name: Deploy mitchellhynes.com to AWS

on:
  push:
    branches: [main]
    paths:
      - "apps/mitchellhynes.com/**"
      - "packages/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install, build, and upload your site
        uses: withastro/action@v2
        with:
          path: ./apps/mitchellhynes.com
          package-manager: yarn

      - name: Deploy to S3
        run: aws s3 sync --delete ./apps/mitchellhynes.com/dist/ s3://${{ secrets.MH_BUCKET_ID }}

      - name: Create CloudFront invalidation
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.MH_DISTRIBUTION_ID }} --paths "/*"
